### ISSUE TITLE
Feature Request: Extend Support For 8 Digit Passcodes

### ISSUE THREAD

**Issue by clutch70** [ImSorryButWho/HomeAssistantNotes#22]
When the passcode is 8 digits, instead of firing one event_type 2 with the event_data filled out, two events of event_type 2 and event_type 1 are fired in immediate succession, resulting in the automation sending a bad passcode sound because the event with event_type 2 has event_data set to NULL.

Request implementation of witchcraft to support 8 digit passcodes.

```
event_type: zwave_js_notification
data:
  domain: zwave_js
  node_id: stuff
  home_id: stuff
  device_id: stuff
  command_class: 111
  command_class_name: Entry Control
  event_type: 1
  event_type_label: Cached keys
  data_type: 2
  data_type_label: ASCII
  event_data: "12345678"
origin: LOCAL
time_fired: "2023-04-07T06:04:41.115338+00:00"
context:
  id: stuf
  parent_id: null
  user_id: null
```

```
event_type: zwave_js_notification
data:
  domain: zwave_js
  node_id: 23
  home_id: stuff
  device_id: stuff
  command_class: 111
  command_class_name: Entry Control
  event_type: 2
  event_type_label: Enter
  data_type: 0
  data_type_label: None
  event_data: null
origin: LOCAL
time_fired: "2023-04-07T06:04:41.530907+00:00"
context:
  id: stuff
  parent_id: null
  user_id: null
```
